from sort_algorithms import SortAlgorithms 
inst_sort_algorithms = SortAlgorithms()
inst_sort_algorithms.burble_sort_function()
inst_sort_algorithms.burble_sort_function_refactor()
inst_sort_algorithms.select_sort_function()